-- Black Mocha · generated by dotctl for Hyprland 0.55+
hl.config({
  general = {
    gaps_in = $gaps_inner,
    gaps_out = $gaps_outer,
    border_size = $border_width,
    col = {
      active_border = "$accent_rgba",
      inactive_border = "$overlay0_rgba",
    },
    layout = "dwindle",
    resize_on_border = true,
  },
  decoration = {
    rounding = $radius,
    active_opacity = 1.0,
    inactive_opacity = 0.96,
    blur = { enabled = $blur, size = 6, passes = 2 },
    shadow = { enabled = $shadows, range = 18, render_power = 3, color = "rgba(000000aa)" },
  },
  input = {
    kb_layout = "us,ru",
    kb_options = "grp:win_space_toggle",
    follow_mouse = 1,
    sensitivity = 0,
    touchpad = { natural_scroll = true, tap_to_click = true, disable_while_typing = true },
  },
  misc = { disable_hyprland_logo = true, disable_splash_rendering = true, vfr = true },
  xwayland = { force_zero_scaling = true },
})

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "$scale" })

hl.animation({ leaf = "windowsIn", enabled = $animations_enabled, speed = 1.6 * $animation_scale, bezier = "default", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = $animations_enabled, speed = 1.3 * $animation_scale, bezier = "default", style = "popin 92%" })
hl.animation({ leaf = "workspaces", enabled = $animations_enabled, speed = 2.2 * $animation_scale, bezier = "default", style = "slide" })
hl.animation({ leaf = "fade", enabled = $animations_enabled, speed = 1.8 * $animation_scale, bezier = "default" })

hl.layer_rule({ match = { namespace = "waybar" }, blur = $blur, ignore_alpha = 0.2 })
hl.layer_rule({ match = { namespace = "quickshell" }, blur = $blur, ignore_alpha = 0.2 })
hl.window_rule({ match = { class = "^(pavucontrol|nm-connection-editor|blueman-manager)$" }, float = true, center = true })
hl.window_rule({ match = { class = "^(yazi-scratchpad)$" }, float = true, size = { "70%", "60%" }, center = true })

require("generated_binds")

for workspace = 1, 10 do
  local key = workspace == 10 and "0" or tostring(workspace)
  hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = workspace }))
  hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = workspace }))
end

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true })
