font_family $font
font_size 11.0
background $base
foreground $text
selection_background $overlay2
selection_foreground $text
cursor $accent
cursor_text_color $base
color0 $base
color1 $red
color2 $green
color3 $yellow
color4 $blue
color5 $accent
color6 $teal
color7 $text
window_padding_width 10
background_opacity 0.96
confirm_os_window_close 0
enable_audio_bell no
shell fish
