[colors]
base = "#000000"
mantle = "#010101"
crust = "#020202"
surface0 = "#070707"
surface1 = "#0B0B0B"
surface2 = "#111111"
overlay0 = "#1A1A1A"
overlay1 = "#222222"
overlay2 = "#2B2B2B"
text = "#CDD6F4"
subtext0 = "#A6ADC8"
subtext1 = "#BAC2DE"
red = "#F38BA8"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
blue = "#89B4FA"
lavender = "#B4BEFE"
